import{a as v,S as w,i as n}from"./assets/vendor-DGqZCHJs.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const q="49636434-6242580fc709b024bc2e20b91",S="https://pixabay.com/api/";async function d(a,t){try{const o=await v.get(`${S}`,{params:{key:q,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return console.log("Response Data:",o.data),o.data}catch(o){throw console.error("Error fetching data:",o),o}}const u=document.querySelector(".loader"),f=document.querySelector(".load-more"),$=document.querySelector(".gallery");let B=new w(".gallery a");function m(a){const t=document.querySelector(".gallery"),o=a.map(({webformatURL:s,largeImageURL:e,tags:r,likes:l,views:p,comments:L,downloads:b})=>`
      <li class="gallery-item">
        <a href="${e}">
          <img src="${s}" alt="${r}" loading="lazy"/>
        </a>
        <div class="info">
          <p>Likes<span>${l}</span></p>
          <p>Views<span>${p}</span></p>
          <p>Comments<span>${L}</span></p>
          <p>Downloads<span>${b}</span></p>
        </div>
      </li>
    `).join("");t.insertAdjacentHTML("beforeend",o),B.refresh()}function M(){$.innerHTML=""}function y(){u.classList.add("visible")}function g(){u.classList.remove("visible")}function E(){f.classList.remove("hidden")}function h(){f.classList.add("hidden")}const I=document.querySelector("#search-form"),O=document.querySelector(".load-more");let c="",i=1;I.addEventListener("submit",async a=>{if(a.preventDefault(),c=a.target.elements.searchQuery.value.trim(),!c){n.error({message:"Please enter a valid search query!"});return}M(),i=1,h(),y();try{const t=await d(c,i);if(!t.hits.length){n.warning({message:"No images found!"});return}m(t.hits),t.totalHits>t.hits.length?E():n.info({message:"We're sorry, but you've reached the end of search results."})}catch{n.error({message:"Failed to fetch images!"})}finally{g()}});O.addEventListener("click",async()=>{i+=1,y();try{const a=await d(c,i);m(a.hits),i*15>=a.totalHits&&(h(),n.info({message:"We're sorry, but you've reached the end of search results."}));const o=document.querySelectorAll(".gallery-item");if(o.length>0){const s=o[0].getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}catch{n.error({message:"Failed to load more images!"})}finally{g()}});await d(c,i);
//# sourceMappingURL=index.js.map
